# Generated by Django 4.2.14 on 2024-07-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [
                    ("can_edit_product_description", "Can edit product description"),
                    ("can_edit_product_category", "Can edit product category"),
                    ("can_cancel_publication", "Can cancel publication of product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
